##FOR LOCAL
#spring.application.name=myservice
#server.port=${PORT:8080}
#
#openai.api.key=${GROQ_API_KEY}
#openai.api.url=https://api.groq.com/openai/v1/chat/completions
#
#
## MySQL Database
#spring.datasource.url=jdbc:mysql://localhost:3306/triviumdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#spring.datasource.username=root
#spring.datasource.password=${MYSQL_PASSWORD}
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
## JPA / Hibernate
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#
#spring.jackson.time-zone=Asia/Kolkata


FOR AIVEN
spring.application.name=myservice
server.port=${PORT:8080}

openai.api.key=${GROQ_API_KEY}
openai.api.url=https://api.groq.com/openai/v1/chat/completions

# MySQL Database (Aiven, via Render env vars)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jackson.time-zone=Asia/Kolkata

logging.level.com.example.myservice=WARN