spring.application.name=myservice
server.port=8080
openai.api.key=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
openai.api.url=https://api.groq.com/openai/v1/chat/completions

# MySQL Real Database
spring.datasource.url=jdbc:mysql://localhost:3306/triviumdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=RootPass_3306!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate - auto creates tables
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
